import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/app.css";
import "./styles/components.css";
import "./styles/markdown.css";
import "./styles/screens.css";
// Generated by tools/genkatex: ~23 KB of rules that reference woff2 faces by
// URL. Loading it eagerly costs almost nothing and removes an async failure
// point; the font files themselves are still fetched only when maths renders.
import "./styles/katex.css";

import * as actions from "../src/actions";
import * as api from "./api";
import { el, qs } from "./lib/dom";
import { openSearchPanel as openEditorSearch, openReplacePanel } from "./lib/find";
import { installShortcuts } from "./shortcuts";
import { setState, state, subscribe } from "./store";
import type { BootstrapPayload, ThemeName } from "./types";
import { openTagsDialog, openTrashDialog } from "./ui/dialogs";
import { bindDocumentTitle, createEditorPane } from "./ui/editorpane";
import { openExportDialog } from "./ui/exportdialog";
import { createNoteList } from "./ui/notelist";
import { buildCommands, openPalette, openSearchPanel } from "./ui/palette";
import { openAbout, openSettings, openShortcuts } from "./ui/settings";
import { createSidebar } from "./ui/sidebar";
import { createStatusbar } from "./ui/statusbar";
import { brandMark, createTabbar, createTitlebar, createWindowControls } from "./ui/titlebar";
import { notify, reportError } from "./ui/toast";

const root = qs(document, "#app");
let teardownView: () => void = () => {};
let updateCheckStarted = false;

// Nothing in a desktop app should fail invisibly. Without this, a rejected
// promise deep in a lazy import just leaves the UI subtly wrong with no clue
// as to why.
window.addEventListener("unhandledrejection", (ev) => {
  const reason = ev.reason;
  const message = reason instanceof Error ? reason.message : String(reason);
  console.error("unhandled rejection", reason);
  notify.error(`出现未处理的错误：${message}`);
});

window.addEventListener("error", (ev) => {
  console.error("uncaught error", ev.error ?? ev.message);
});

// Wails' EnableDefaultContextMenu:false still lets WebView2 show its own menu
// over editable regions, and the editor is editable. Suppressing it here in the
// capture phase guarantees the app's own menus are the only ones that appear;
// the event still bubbles on to whichever component builds that menu.
document.addEventListener(
  "contextmenu",
  (ev) => ev.preventDefault(),
  { capture: true },
);

/* ---------------------------------------------------------------- theme */

const systemDark = window.matchMedia("(prefers-color-scheme: dark)");

function resolveTheme(theme: ThemeName): "light" | "dark" {
  if (theme === "system") return systemDark.matches ? "dark" : "light";
  return theme;
}

function applyTheme(theme: ThemeName): void {
  const resolved = resolveTheme(theme);
  document.documentElement.dataset.theme = resolved;
  document.documentElement.style.background = "";
  // Read by the inline script in index.html on the next launch, so a dark
  // startup never flashes white before the bundle loads.
  try {
    localStorage.setItem("qiaoji.theme", theme);
  } catch {
    /* storage unavailable; the flash guard simply falls back to light */
  }
  // Keep the native window frame, resize border and snap preview in step.
  void api.applyTheme(theme === "system" ? "system" : resolved);
}

function setTheme(theme: ThemeName): void {
  applyTheme(theme);
  void actions.patchSettings({ theme });
}

systemDark.addEventListener("change", () => {
  if (state.settings.theme === "system") applyTheme("system");
});

function applyZoom(): void {
  document.documentElement.style.setProperty("--ui-scale", String(state.settings.zoom / 100));
}

/* ---------------------------------------------------------------- shell */

function buildShell(): () => void {
  const editorPane = createEditorPane({
    onCursor: (line, column, selected) => statusbar.setCursor(line, column, selected),
  });

  const statusbar = createStatusbar({
    setMode: (mode) => editorPane.setMode(mode),
  });

  const paletteDeps = {
    toggleMode: () => editorPane.toggleMode(),
    openExport: () => openExportDialog({ currentHtml: editorPane.currentHtml }),
    openSettings: () => openSettings(settingsDeps),
    openShortcuts,
    openAbout,
    openTrash: openTrashDialog,
    openTags: openTagsDialog,
    openSearch: () => openSearchPanel(),
    openFind: () => openEditorSearch(editorPane.editor.view),
    openReplace: () => openReplacePanel(editorPane.editor.view),
    setTheme,
    toggleSidebar: () => setState({ sidebarVisible: !state.sidebarVisible }),
  };

  const settingsDeps = {
    openShortcuts,
    openAbout,
    setTheme,
  };

  const commands = buildCommands(paletteDeps);

  const titlebar = createTitlebar({
    openPalette: () => openPalette(commands),
    openSearch: () => openSearchPanel(),
    openSettings: () => openSettings(settingsDeps),
    toggleSidebar: paletteDeps.toggleSidebar,
  });

  const tabbar = createTabbar({
    newNote: () => void actions.newNote(),
    toggleList: () => setState({ listVisible: !state.listVisible }),
    toggleMode: () => editorPane.toggleMode(),
    openExport: paletteDeps.openExport,
    openOutline: (anchor) => editorPane.showOutline(anchor),
  });

  const sidebar = createSidebar({
    openTrash: openTrashDialog,
    openTags: openTagsDialog,
    openSettings: () => openSettings(settingsDeps),
  });

  const notelist = createNoteList();
  const body = el("div", { class: "body" }, sidebar, notelist, editorPane.root);
  const shell = el("div", { class: "shell" }, titlebar, tabbar, body, statusbar.root);

  root.replaceChildren(shell);

  const paintLayout = () => {
    body.classList.toggle("is-sidebar-hidden", !state.sidebarVisible);
    // Grid view owns the whole content area, so the list cannot also be hidden.
    body.classList.toggle("is-grid", state.listView === "grid");
    body.classList.toggle(
      "is-list-hidden",
      !state.listVisible && state.listView !== "grid",
    );
  };
  const unsubscribeLayout = subscribe(["sidebarVisible", "listVisible", "listView"], paintLayout);
  paintLayout();

  const unsubscribeTitle = bindDocumentTitle();
  const unsubscribeZoom = subscribe(["settings"], applyZoom);

  /* -------------------------------------------------------- shortcuts */

  const uninstallShortcuts = installShortcuts(
    [
      { key: "n", ctrl: true, run: () => void actions.newNote() },
      { key: "o", ctrl: true, run: () => openPalette(commands) },
      { key: "s", ctrl: true, run: () => void actions.saveActive() },
      // Shift, because the global layer runs in the capture phase and stops
      // propagation: a plain Ctrl+E here meant the editor's inline-code
      // binding could never fire, though three places advertised it.
      { key: "e", ctrl: true, shift: true, run: paletteDeps.openExport },
      {
        key: "w",
        ctrl: true,
        run: () => {
          if (state.activeTabId) void actions.closeTab(state.activeTabId);
        },
      },
      { key: "p", ctrl: true, run: () => editorPane.toggleMode() },
      { key: "p", ctrl: true, shift: true, global: true, run: () => openPalette(commands) },
      { key: "f", ctrl: true, run: () => openEditorSearch(editorPane.editor.view) },
      { key: "f", ctrl: true, shift: true, run: () => openSearchPanel() },
      { key: "h", ctrl: true, run: () => openReplacePanel(editorPane.editor.view) },
      { key: "\\", ctrl: true, run: paletteDeps.toggleSidebar },
      { key: ",", ctrl: true, run: () => openSettings(settingsDeps) },
      { key: "/", ctrl: true, run: openShortcuts },
      { key: "tab", ctrl: true, run: () => actions.cycleTab(1) },
      { key: "tab", ctrl: true, shift: true, run: () => actions.cycleTab(-1) },
      { key: "1", ctrl: true, alt: true, run: () => actions.selectScope("all") },
      { key: "2", ctrl: true, alt: true, run: () => actions.selectScope("recent") },
      { key: "3", ctrl: true, alt: true, run: () => actions.selectScope("favorites") },
    ],
    // Escape falls back to leaving preview mode, then to focusing the editor.
    () => {
      const tab = state.tabs.find((t) => t.id === state.activeTabId);
      if (tab?.mode === "preview") {
        editorPane.setMode("edit");
        return true;
      }
      if (state.searchHits !== null) {
        actions.clearSearch();
        return true;
      }
      return false;
    },
  );

  /* -------------------------------------------------------- backend events */

  const unsubscribeBackend = [
    api.onBackend("vault:changed", (payload) => {
      const external = (payload as { external?: boolean } | undefined)?.external ?? true;
      actions.refreshAllSoon();
      if (external) void actions.reconcileTabs();
    }),
    api.onBackend("tray:new-note", () => void actions.newNote()),
    api.onBackend("window:focus", () => {
      editorPane.focus();
    }),
  ];

  // The Go side vetoes the close and waits for this answer, so the process
  // cannot exit while the flush is still in flight.
  unsubscribeBackend.push(
    api.onBackend("app:before-close", (payload) => {
      const quitting = (payload as { quitting?: boolean } | undefined)?.quitting ?? true;
      void (async () => {
        const flushed = await actions.saveAll();
        if (flushed) {
          if (quitting) await api.confirmClose();
          return;
        }
        // Losing the edit is worse than an unexpected window. Coming back from
        // the tray matters most: hidden, there is nowhere to show the error.
        await (quitting ? api.cancelClose() : api.showWindow());
        notify.error("有笔记未能保存，请检查笔记库所在磁盘");
      })();
    }),
  );

  // A last-ditch flush for kill paths that skip the graceful close.
  const beforeUnload = () => {
    void actions.saveAll();
  };
  window.addEventListener("beforeunload", beforeUnload);

  const onBlur = () => {
    if (state.settings.autoSave) void actions.saveAll();
  };
  window.addEventListener("blur", onBlur);

  return () => {
    window.removeEventListener("beforeunload", beforeUnload);
    window.removeEventListener("blur", onBlur);
    for (const unsubscribe of unsubscribeBackend) unsubscribe();
    uninstallShortcuts();
    unsubscribeLayout();
    unsubscribeTitle();
    unsubscribeZoom();
    titlebar.destroy();
    tabbar.destroy();
    sidebar.destroy();
    notelist.destroy();
    statusbar.destroy();
    editorPane.destroy();
    shell.remove();
  };
}

/* ---------------------------------------------------------------- boot */

function adoptPayload(payload: BootstrapPayload): void {
  setState({
    ready: payload.vaultReady,
    settings: payload.settings,
    version: payload.version,
    vaultPath: payload.vaultPath,
    stats: payload.stats,
    listView: payload.settings.listView,
    sortBy: payload.settings.sortBy,
  });
  applyTheme(payload.settings.theme);
  applyZoom();
}

function checkUpdatesOnLaunch(): void {
  if (
    updateCheckStarted ||
    !state.settings.autoUpdate ||
    state.version === "dev"
  ) {
    return;
  }
  updateCheckStarted = true;
  void api
    .checkForUpdates()
    .then((info) => {
      if (!info.available) return;
      notify.info(`巧记 ${info.latestVersion} 已发布`, {
        duration: 12_000,
        action: {
          label: "查看更新",
          run: () => void api.openExternal(info.releaseUrl).catch((err) => reportError("打开更新页面", err)),
        },
      });
    })
    // Offline launches should remain quiet. The API facade already records the
    // failure in the Wails log for diagnosis; manual checks report it onscreen.
    .catch(() => {});
}

/**
 * Shown only when the library folder cannot be opened at all, for example
 * because it lives on a drive that is currently disconnected. There is no
 * first-run screen: a healthy launch goes straight into the app.
 */
function showVaultError(message: string): void {
  teardownView();
  const retry = el(
    "button",
    {
      class: "btn btn--primary",
      type: "button",
      onclick: () => {
        retry.disabled = true;
        void start();
      },
    },
    "重试",
  );

  const controls = createWindowControls();
  const screen = el(
      "div",
      { class: "welcome-screen" },
      el(
        "header",
        { class: "titlebar titlebar--bare" },
        brandMark("titlebar__mark"),
        el("span", { class: "titlebar__title" }, "巧记"),
        el("div", { class: "spacer" }),
        controls,
      ),
      el(
        "div",
        { class: "empty", style: { background: "var(--bg-app)" } },
        el("div", { class: "empty__title" }, "无法打开笔记库"),
        el("div", { class: "empty__hint" }, message),
        el(
          "div",
          { style: { display: "flex", gap: "var(--sp-3)" } },
          retry,
          el(
            "button",
            {
              class: "btn",
              type: "button",
              onclick: async () => {
                const dir = await api.selectVaultDir().catch(() => "");
                if (!dir) return;
                const next = await api.openVault(dir).catch((err) => {
                  reportError("打开笔记库", err);
                  return null;
                });
                if (next?.vaultReady) {
                  adoptPayload(next);
                  void enterApp(next);
                }
              },
            },
            "选择其他文件夹",
          ),
        ),
      ),
    );
  root.replaceChildren(screen);
  teardownView = () => {
    controls.destroy();
    screen.remove();
  };
}

async function start(): Promise<void> {
  let payload: BootstrapPayload;
  try {
    payload = await api.bootstrap();
  } catch (err) {
    showVaultError(err instanceof Error ? err.message : String(err));
    return;
  }

  adoptPayload(payload);

  if (!payload.vaultReady) {
    showVaultError(payload.error || "笔记库文件夹不可访问。");
    return;
  }
  await enterApp(payload);
}

async function enterApp(payload: BootstrapPayload): Promise<void> {
  teardownView();
  teardownView = buildShell();

  await actions.refreshAll();

  // Reopen the most recently edited note so the app never starts on a blank
  // screen when there is obvious work in progress.
  const first = state.notes[0];
  if (first) await actions.openNote(first, { focus: false });

  if (payload.error) notify.error(payload.error);
  checkUpdatesOnLaunch();
}

void start();
