// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {store} from '../models';
import {exporter} from '../models';
import {config} from '../models';
import {index} from '../models';

export function ApplyTheme(arg1:string):Promise<void>;

export function ApplyUpdate():Promise<void>;

export function Bootstrap():Promise<main.Bootstrap>;

export function CancelClose():Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ConfirmClose():Promise<void>;

export function CreateFolder(arg1:string):Promise<store.Folder>;

export function CreateNote(arg1:string,arg2:string):Promise<store.Note>;

export function DeleteFolder(arg1:string):Promise<store.TrashItem>;

export function DeleteNote(arg1:string):Promise<store.TrashItem>;

export function DeleteTag(arg1:string):Promise<number>;

export function DuplicateNote(arg1:string):Promise<store.Meta>;

export function EmptyTrash():Promise<void>;

export function Export(arg1:exporter.Request):Promise<string>;

export function GetNote(arg1:string,arg2:string):Promise<store.Note>;

export function GetSettings():Promise<config.Settings>;

export function ListFolders():Promise<Array<store.Folder>>;

export function ListNotes(arg1:index.Query):Promise<Array<store.Meta>>;

export function ListTags():Promise<Array<store.Tag>>;

export function ListTrash():Promise<Array<store.TrashItem>>;

export function MoveNote(arg1:string,arg2:string):Promise<store.Meta>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenVault(arg1:string):Promise<main.Bootstrap>;

export function PurgeTrashItem(arg1:string):Promise<void>;

export function RebuildIndex():Promise<main.Stats>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameNote(arg1:string,arg2:string):Promise<store.Meta>;

export function RenameTag(arg1:string,arg2:string):Promise<number>;

export function RequestQuit():Promise<void>;

export function RestoreNote(arg1:string):Promise<store.Restored>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveAsset(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function SaveNote(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<store.Meta>;

export function SaveSettings(arg1:config.Settings):Promise<config.Settings>;

export function SaveWindowState(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<index.Hit>>;

export function SelectExportDir():Promise<string>;

export function SelectVaultDir():Promise<string>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<store.Meta>;

export function SetNoteTags(arg1:string,arg2:Array<string>):Promise<store.Meta>;

export function ShowWindow():Promise<void>;

export function Sidebar():Promise<main.SidebarData>;

export function SortedFolderNames():Promise<Array<string>>;

export function Stats():Promise<main.Stats>;

export function Suggest(arg1:string,arg2:number):Promise<Array<store.Meta>>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<boolean>;
