// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTheme(arg1) {
  return window['go']['main']['App']['ApplyTheme'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CancelClose() {
  return window['go']['main']['App']['CancelClose']();
}

export function ConfirmClose() {
  return window['go']['main']['App']['ConfirmClose']();
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DuplicateNote(arg1) {
  return window['go']['main']['App']['DuplicateNote'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function GetNote(arg1, arg2) {
  return window['go']['main']['App']['GetNote'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function ListTrash() {
  return window['go']['main']['App']['ListTrash']();
}

export function MoveNote(arg1, arg2) {
  return window['go']['main']['App']['MoveNote'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenVault(arg1) {
  return window['go']['main']['App']['OpenVault'](arg1);
}

export function PurgeTrashItem(arg1) {
  return window['go']['main']['App']['PurgeTrashItem'](arg1);
}

export function RebuildIndex() {
  return window['go']['main']['App']['RebuildIndex']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['App']['RenameNote'](arg1, arg2);
}

export function RenameTag(arg1, arg2) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function SaveNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWindowState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2, arg3, arg4, arg5);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SelectExportDir() {
  return window['go']['main']['App']['SelectExportDir']();
}

export function SelectVaultDir() {
  return window['go']['main']['App']['SelectVaultDir']();
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function SetNoteTags(arg1, arg2) {
  return window['go']['main']['App']['SetNoteTags'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Sidebar() {
  return window['go']['main']['App']['Sidebar']();
}

export function SortedFolderNames() {
  return window['go']['main']['App']['SortedFolderNames']();
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function Suggest(arg1, arg2) {
  return window['go']['main']['App']['Suggest'](arg1, arg2);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
