// Command genkatex vendors KaTeX's stylesheet into a single self-contained CSS
// file with the woff2 faces inlined as data URIs.
//
// Exported HTML has to render maths on a machine that never installed the app,
// and the headless-Edge PDF pass has to work with no network. One inlined
// stylesheet satisfies both without shipping 60 font files.
//
// Run from the repository root after upgrading KaTeX:
//
//	go run ./tools/genkatex
package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	distDir = "frontend/node_modules/katex/dist"
	// Self-contained sheet for exported HTML and the headless-Edge PDF pass.
	outFile = "internal/exporter/assets/katex-inline.css"
	// Sheet for the app bundle. WebView2 is Chromium, so the woff and ttf
	// fallbacks in the stock stylesheet are dead weight that Vite would
	// otherwise copy into the binary: 40 extra files, roughly 800 KB.
	appFile = "frontend/src/styles/katex.css"
)

// Matches a full src: declaration inside an @font-face block.
var srcRe = regexp.MustCompile(`src:[^;}]*`)

// Matches one url(fonts/Name.woff2) reference.
var woff2Re = regexp.MustCompile(`url\(fonts/([A-Za-z0-9_\-]+\.woff2)\)`)

func main() {
	css, err := os.ReadFile(filepath.Join(distDir, "katex.min.css"))
	if err != nil {
		fatal("read katex.min.css: %v", err)
	}

	cache := map[string]string{}
	inlined := 0

	out := srcRe.ReplaceAllStringFunc(string(css), func(decl string) string {
		m := woff2Re.FindStringSubmatch(decl)
		if m == nil {
			return decl // no woff2 in this face; leave it untouched
		}
		name := m[1]
		data, ok := cache[name]
		if !ok {
			raw, err := os.ReadFile(filepath.Join(distDir, "fonts", name))
			if err != nil {
				fatal("read font %s: %v", name, err)
			}
			data = base64.StdEncoding.EncodeToString(raw)
			cache[name] = data
			inlined++
		}
		return fmt.Sprintf(`src:url(data:font/woff2;base64,%s) format("woff2")`, data)
	})

	if inlined == 0 {
		fatal("no woff2 faces found; did the KaTeX layout change?")
	}

	// The bundled sheet keeps real URLs so the bundler can fingerprint and
	// lazily fetch each face, but drops every non-woff2 source.
	linked := srcRe.ReplaceAllStringFunc(string(css), func(decl string) string {
		m := woff2Re.FindStringSubmatch(decl)
		if m == nil {
			return decl
		}
		return fmt.Sprintf(`src:url(../../node_modules/katex/dist/fonts/%s) format("woff2")`, m[1])
	})

	header := "/* Generated by tools/genkatex from katex.min.css. Do not edit. */\n"
	write(outFile, header+out)
	write(appFile, header+linked)

	fmt.Printf("wrote %s (%d fonts inlined, %s)\n", outFile, inlined, humanKB(len(header)+len(out)))
	fmt.Printf("wrote %s (woff2 only, %s)\n", appFile, humanKB(len(header)+len(linked)))
}

func write(path, content string) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fatal("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fatal("write %s: %v", path, err)
	}
}

func humanKB(n int) string { return fmt.Sprintf("%.0f KB", float64(n)/1024) }

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genkatex: "+strings.TrimSuffix(format, "\n")+"\n", args...)
	os.Exit(1)
}
